/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nuzrath
 */
public class ConTestAndMsgBoxes extends javax.swing.JFrame {

    /**
     * Creates new form ConTestAndMsgBoxes
     */
    public ConTestAndMsgBoxes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMsgBox = new javax.swing.JButton();
        btnTestDB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnMsgBox.setText("MsgBox");
        btnMsgBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMsgBoxActionPerformed(evt);
            }
        });
        getContentPane().add(btnMsgBox);
        btnMsgBox.setBounds(180, 70, 210, 60);

        btnTestDB.setText("Test DB");
        btnTestDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestDBActionPerformed(evt);
            }
        });
        getContentPane().add(btnTestDB);
        btnTestDB.setBounds(180, 150, 210, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMsgBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMsgBoxActionPerformed
        //JOptionPane.showMessageDialog(this,"Be happy 4ever","My Wish",JOptionPane.INFORMATION_MESSAGE);
        //JOptionPane.showMessageDialog(this,"This will reset your password","Warning",JOptionPane.WARNING_MESSAGE);
        //JOptionPane.showMessageDialog(this,"Record Not Found","Failure",JOptionPane.ERROR_MESSAGE);
        int res = JOptionPane.showConfirmDialog(this,"Are you sure you want to exit this program?","Are you sure",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(res == JOptionPane.YES_OPTION){
            System.exit(0);
        }

    }//GEN-LAST:event_btnMsgBoxActionPerformed

    private void btnTestDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestDBActionPerformed

        try {
            DataBase db = new DataBase();

            String CID,name,address,due;
            CID = txtCID.getText();
            name = txtName.getText();
            address = txtAddress.getText();
            due = txtDue.getText();

            //creating the sql command
            //String sql = "INSERT INTO customer VALUES(NULL,'Peter','Kegalle',5000)";;

            String sql = "INSERT INTO customer values(NULL,";

            sql += "'" + name + "',";
            sql += "'" + address + "',";
            sql += due + ")";

            System.out.println(sql);

            //execute the sql command
            int x = db.executeUpdate(sql);
            if(x>0){
                JOptionPane.showMessageDialog(this,"Record Successfully saved","Success",JOptionPane.INFORMATION_MESSAGE);
                clearText();
                txtName.requestFocus();
            }
            else{
                JOptionPane.showMessageDialog(this,"saving new record failed","failure",JOptionPane.ERROR_MESSAGE);
            }

            System.out.println(x);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }//GEN-LAST:event_btnTestDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConTestAndMsgBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConTestAndMsgBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConTestAndMsgBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConTestAndMsgBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConTestAndMsgBoxes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMsgBox;
    private javax.swing.JButton btnTestDB;
    // End of variables declaration//GEN-END:variables
}
