
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class CustomerMaint extends javax.swing.JFrame {

    private String mode = "UNKNOWN";
    DataBase db = new DataBase();
    
    public CustomerMaint() {
        initComponents();
        setSize(800,600);
        clearText();
        disableText();
        enableButtons();
    }
    
    public void clearText(){
        txtCID.setText("");
        txtName.setText("");
        txtAddress.setText("");
        txtDue.setText("");        
    }
    
    //enable all buttons
    public void enableButtons(){
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);
        btnClose.setEnabled(true);
    }
    
    //disable all buttons
    public void disableButtons(){
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        btnSave.setEnabled(false);
        btnCancel.setEnabled(true);
        btnClose.setEnabled(false);
    }
    
    //disale all text fields
    public void disableText(){
        txtCID.setEnabled(false);
        txtName.setEnabled(false);
        txtAddress.setEnabled(false);
        txtDue.setEnabled(false);
    }
    
    //enabale all text fields
    public void enableText(){
        txtCID.setEnabled(true);
        txtName.setEnabled(true);
        txtAddress.setEnabled(true);
        txtDue.setEnabled(true);
    }
    
    //this code valiades the fields for values 
    public boolean isAllValid(){
        if(txtCID.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Customer ID Cannot be blank","Error",JOptionPane.ERROR_MESSAGE);
            txtCID.requestFocus();
            return false;
        }
        else if(txtName.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Name cannot be empty","Error",JOptionPane.ERROR_MESSAGE);
            txtName.requestFocus();
            return false;
        }
        else if(txtAddress.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Address cannot be empty","Error",JOptionPane.ERROR_MESSAGE);
            txtAddress.requestFocus();
            return false;
        }
        else if(txtDue.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Due Amount Amount be empty","Error",JOptionPane.ERROR_MESSAGE);
            txtDue.requestFocus();
            return false;
        }
        else{
            return true;
        }
        
    }
    
    //creating a function to search and display
    //the record contents when customer id is
    //given
    public void displayRecord(String cid){
        String sql = "select * from customer where cid="+cid;
        ResultSet rs = db.executeQuery(sql);
        try {
            if(rs.next()){
                //lets display the record
                txtName.setText(rs.getString("name"));
                txtAddress.setText(rs.getString("address"));
                txtDue.setText(rs.getString("due"));
            }
            else{
                JOptionPane.showMessageDialog(this,"Sorry No Matching Records were found","Error",JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.toString(),"Error",JOptionPane.ERROR);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDue = new javax.swing.JTextField();
        btnTestDB = new javax.swing.JButton();
        btnMsgBox = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Customer ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 30, 90, 30);

        txtCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtCID);
        txtCID.setBounds(40, 60, 100, 30);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 30, 90, 30);
        getContentPane().add(txtName);
        txtName.setBounds(160, 60, 210, 30);

        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 30, 90, 30);
        getContentPane().add(txtAddress);
        txtAddress.setBounds(380, 60, 190, 30);

        jLabel4.setText("Due Amount");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 30, 90, 30);

        txtDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDueActionPerformed(evt);
            }
        });
        getContentPane().add(txtDue);
        txtDue.setBounds(600, 60, 100, 30);

        btnTestDB.setText("Test DB");
        btnTestDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestDBActionPerformed(evt);
            }
        });
        getContentPane().add(btnTestDB);
        btnTestDB.setBounds(680, 10, 100, 30);

        btnMsgBox.setText("MsgBox");
        btnMsgBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMsgBoxActionPerformed(evt);
            }
        });
        getContentPane().add(btnMsgBox);
        btnMsgBox.setBounds(580, 10, 90, 23);

        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(613, 110, 90, 40);

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(40, 110, 90, 40);

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit);
        btnEdit.setBounds(170, 110, 70, 40);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(270, 110, 100, 40);

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(380, 110, 100, 40);

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(500, 110, 90, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnTestDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestDBActionPerformed

        try {
            DataBase db = new DataBase();
            
            String CID,name,address,due;
            CID = txtCID.getText();
            name = txtName.getText();
            address = txtAddress.getText();
            due = txtDue.getText();
            
            //creating the sql command
            //String sql = "INSERT INTO customer VALUES(NULL,'Peter','Kegalle',5000)";;
            
            String sql = "INSERT INTO customer values(NULL,";
            
            sql += "'" + name + "',";
            sql += "'" + address + "',";
            sql += due + ")";
            
            System.out.println(sql);
            
            
            
            //execute the sql command
            int x = db.executeUpdate(sql);
            if(x>0){
                JOptionPane.showMessageDialog(this,"Record Successfully saved","Success",JOptionPane.INFORMATION_MESSAGE);
                clearText();
                txtName.requestFocus();
            }
            else{
                JOptionPane.showMessageDialog(this,"saving new record failed","failure",JOptionPane.ERROR_MESSAGE);
            }
                 
            
            
            System.out.println(x);
            
            
            
            
            
            
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        
    }//GEN-LAST:event_btnTestDBActionPerformed

    private void btnMsgBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMsgBoxActionPerformed
        //JOptionPane.showMessageDialog(this,"Be happy 4ever","My Wish",JOptionPane.INFORMATION_MESSAGE);
        //JOptionPane.showMessageDialog(this,"This will reset your password","Warning",JOptionPane.WARNING_MESSAGE);
        //JOptionPane.showMessageDialog(this,"Record Not Found","Failure",JOptionPane.ERROR_MESSAGE);
        int res = JOptionPane.showConfirmDialog(this,"Are you sure you want to exit this program?","Are you sure",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(res == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_btnMsgBoxActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        int res = JOptionPane.showConfirmDialog(this,"Are you sure you want to exit this program?","Are you sure",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(res == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        mode = "ADD";
        disableButtons();
        enableText();
        txtName.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        mode = "EDIT";
        disableButtons();
        enableText();
        txtCID.requestFocus();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        mode = "DELETE";
        disableButtons();
        enableText();
        txtCID.requestFocus();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearText();
        disableText();
        enableButtons();
    }//GEN-LAST:event_btnCancelActionPerformed

    
    
    private void txtDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDueActionPerformed
        
        if(isAllValid()){
            //every field is properly filled
            btnSave.setEnabled(true);
            btnSave.requestFocus();
        }
        
        
    }//GEN-LAST:event_txtDueActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if(isAllValid()){
            //everything fine lets add or edit
            
            String cid,name,address,due;
            cid     = txtCID.getText().trim();
            name    = txtName.getText().trim();
            address = txtAddress.getText().trim();
            due     = txtDue.getText().trim();
            
            String sql = "";
            
            if(mode.equals("ADD")){
                sql = "insert into customer (name,address,due) values(";
                sql += "'"+name+"',";
                sql += "'"+address+"',";
                sql += ""+due+")";
            }
            else{//edit delete
                sql = "update customer set ";
                sql += "name='"+name+"',";
                sql += "address='"+address+"',";
                sql += "due="+due+" "; //last space must
                sql += " where cid=" + cid;
            }
            //lets execute the code
            int x = db.executeUpdate(sql);
            if(x > 0){
                JOptionPane.showMessageDialog(this,"successfully saved!","Success",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                //failure
                JOptionPane.showMessageDialog(this,"Saving Failed","Error",JOptionPane.INFORMATION_MESSAGE);
                //System.out.println(sql);
            }
            //reset the screen
            clearText();
            disableText();
            enableButtons();
        }
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCIDActionPerformed

        if(mode.equals("EDIT") || mode.equals("DELETE")){
            displayRecord(txtCID.getText());
        }
        
        if(mode.equals("DELETE")){
            if(!txtCID.getText().trim().equals("")){
                String cid = txtCID.getText().trim();
                String sql = "delete from customer where cid="+cid;
                
                int res = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete this record?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(res == JOptionPane.YES_OPTION){
                    int x = db.executeUpdate(sql);
                    if(x > 0){
                    JOptionPane.showMessageDialog(this,"Record Successfully Delete","Success",JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Delete Record Failed","Error",JOptionPane.ERROR_MESSAGE);
                    }
                }
                clearText();
                disableText();
                enableButtons();
            }
        }
        
        
    }//GEN-LAST:event_txtCIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnMsgBox;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTestDB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCID;
    private javax.swing.JTextField txtDue;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
